//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23MCA028_Exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBookM
    {
        public int id { get; set; }
        public string name { get; set; }
        public string isbn { get; set; }
        public decimal price { get; set; }
        public string author { get; set; }
        public int quantity { get; set; }
    }
}
